# SITE CONFIGURATION
baseurl: ""
url: "windchillblog.com"
title: WindChillBlog # site's title
description: "My blog for useful code" # used by search engines
future: true

defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: assets/img/wind_icon.png # seo tag

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/wind_icon.png
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/wind_icon.ico

  # Header and footer text
  header_text: 
  header_feature_image: 
  footer_text: Copyright WindChillMedia 2020

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble: 
  facebook:
  flickr:
  gitlab:
  github: "thecoolwinter"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "https://stackoverflow.com/users/10453550/thecoolwinter" # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus:
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin:
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics:  "UA-158895203-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "windchillblog"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next Page"
  str_previous_page: "Previos Page"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# AUTHORS
authors:
  thecoolwinter:
    name: Khan Winter
    avatar: "assets/img/avatars/Khan.jpg"
    url: "https://thecoolwinter.github.io"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]
# theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
